name: zappy-snapshot-publisher
run-name: Publishing a snapshot of zappy library
on:
  workflow_dispatch:
env:
  # GRADLE_JAVA_VERSION: 17
  JAVA_VERSION: 21
  GRADLE_VERSION: 8.8
  PROJECT_NAME: zappy
  VERSION_FILE_PATH: ${{ github.workspace }}/version
jobs:
  sanity_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: |
          version="v$(head -n 1 ${{ env.VERSION_FILE_PATH }})"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Snapshot test
        working-directory: code
        run: |
          if [[ "${{ github.ref_name }}" != "dev" ]]; then
            echo "Snapshots are only allowed on dev branch!"
            exit 1
          fi
          if [[ "${{ steps.version.outputs.version }}" != *"-SNAPSHOT" ]]; then
            echo "Only snapshots are allowed on dev branch!"
            exit 1
          fi

  snapshot_package:
    needs: sanity_check
    permissions:
      packages: write # Packages.
      id-token: write # Pages.
      pages: write    # Pages.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup Java for Gradle
      #   uses: oracle-actions/setup-java@v1
      #   with:
      #     release: ${{ env.GRADLE_JAVA_VERSION }}

      - name: Setup Java
        uses: oracle-actions/setup-java@v1
        with:
          release: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Test
        working-directory: code
        run: gradle :${{ env.PROJECT_NAME }}:test

      - name: Build
        working-directory: code
        run: gradle :${{ env.PROJECT_NAME }}:build

      - name: Recreate GPG keys
        run: echo "${{ secrets.GPG_KEYS_BASE64 }}" | base64 -d > "${{ github.workspace }}/gpg-keys"

      - name: Publish
        working-directory: code
        run: |
          gradle \
            "-Pgpr.username=${{ github.actor }}" \
            "-Pgpr.token=${{ secrets.GITHUB_TOKEN }}" \
            "-Psigning.keyId=${{ secrets.GPG_KEY_ID }}" \
            "-Psigning.password=${{ secrets.GPG_PASSWORD }}" \
            "-Psigning.secretKeyRingFile=${{ github.workspace }}/gpg-keys" \
            :${{ env.PROJECT_NAME }}:publish

      - name: Clean up old snapshots
        uses: actions/delete-package-versions@v5
        with:
          package-name: com.glitchybyte.zappy.zappy
          package-type: maven
          min-versions-to-keep: 1
          delete-only-pre-release-versions: "true"
